[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/api/chat"
  status = 200
  force = true

[[redirects]]
  from = "/chat-with-file"
  to = "/.netlify/functions/api/chat-with-file"
  status = 200
  force = true

[[redirects]]
  from = "/history/*"
  to = "/.netlify/functions/api/history/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/chat-with-upload.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/chat-with-upload.html"
  status = 200
